name: kestrel

services:
  gateway:
    build:
      context: .
      dockerfile: crates/services/gateway/Dockerfile

    volumes:
      - ./kestrel.toml:/var/kestrel/conf.toml:ro
    environment:
      - KESTREL_CONFIG=/var/kestrel/conf.toml

    ports:
      - "5180:5180"

    restart: unless-stopped

    profiles: ["prod", "dev"]

  api:
    build:
      context: .
      dockerfile: crates/services/api/Dockerfile

    volumes:
      - ./kestrel.toml:/var/kestrel/conf.toml:ro
    environment:
      - KESTREL_CONFIG=/var/kestrel/conf.toml

    ports:
      - "5181:5181"

    restart: unless-stopped

    profiles: ["prod", "dev"]

  postgres:
    image: postgres:18

    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: kestrel
      POSTGRES_PASSWORD: kestrel
      POSTGRES_DB: kestrel

    ports:
      - "5432:5432"

    restart: unless-stopped

    profiles: ["dev"]

volumes:
  postgres_data:
