name: kestrel

services:
  dendryte:
    container_name: dendryte
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_MODE: ${BUILD_MODE:-debug}

    volumes:
      - ./dendryte.toml:/var/dendryte/conf.toml:ro,z
    environment:
      - crate::config=/var/dendryte/conf.toml

    ports:
      - "5187:5187"

    restart: unless-stopped

    profiles: ["prod", "dev"]

  postgres:
    container_name: postgres
    image: postgres:18

    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: dendryte
      POSTGRES_PASSWORD: dendryte
      POSTGRES_DB: dendryte

    ports:
      - "5432:5432"

    restart: unless-stopped

    profiles: ["dev"]

  redis:
    container_name: redis
    image: redis:7-alpine

    command: ["redis-server", "--appendonly", "yes"]

    volumes:
      - redis_data:/data

    ports:
      - "6379:6379"

    restart: unless-stopped

    profiles: ["dev"]

volumes:
  postgres_data:
  redis_data:
