name: kestrel

services:
  dendryte:
    container_name: dendryte
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_MODE: debug

    volumes:
      - ./dendryte.toml:/var/dendryte/conf.toml:ro,z
    environment:
      - DENDRYTE_CONFIG=/var/dendryte/conf.toml

    ports:
      - "5187:5187"

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5187/"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3

  postgres:
    container_name: postgres
    image: postgres:18

    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: dendryte
      POSTGRES_PASSWORD: dendryte
      POSTGRES_DB: dendryte

    ports:
      - "5432:5432"

    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:7-alpine

    command: ["redis-server", "--appendonly", "yes"]

    volumes:
      - redis_data:/data

    ports:
      - "6379:6379"

    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
