# Used to allow email@localhost on registration
is_production = false

[instance]
name = "My Kestrel Instance"
domain = "domain.tld"

# Optional
description = "My awesome Kestrel server"

[server]
# Host must be 0.0.0.0 if you are hosting via Docker!
host = "0.0.0.0"

[server.ports]
gateway = 5180
api = 5181

[server.cors]
# allowed_origins defines which domains are permitted to make cross-origin requests.
# Use ["*"] to allow any website or web client to access the API.
# You can also restrict this to specific origins, e.g. ["https://kestrel.chat"].
allowed_origins = ["*"]
allow_credentials = false

[database.postgres]
url = "postgresql://kestrel:kestrel@postgres:5432/kestrel"

[database.redis]
url = "redis://redis:6379"

[features.hcaptcha]
enabled = false

# Your hCaptcha site key.
# Required when enabled = true.
# sitekey = "00000000-0000-0000-0000-000000000000"

# Your hCaptcha secret key.
# Required when enabled = true.
# secret = "ES_000000000000001"

[features.registration]
enabled = true
minimum_age = 16
