is_production = false

[network]
# This must be 0.0.0.0 if you are hosting via Docker (recommended)
host = "0.0.0.0"
# By default we will allocate ports 5180-5189 to Kestrel. This does not include external services like Postgres.
ports = { gateway = 5180, api = 5181 }

[network.cors]
allowed_origins = ["*"]
allow_credentials = true

[database]
postgres = "postgresql://kestrel:kestrel@postgres:5432/kestrel"
redis = "redis://redis:6379"

[hcaptcha]
secret = "ES_000000000000001"

[api.registration]
minimum_age = 16
