[package]
name = "kestrel_postgres"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.44", features = ["serde"] }
kestrel_common = { version = "0.1.0", path = "../common" }
sqlx = { version = "0.8.6", features = ["chrono", "postgres", "runtime-tokio-native-tls"] }
thiserror = "2.0.18"
ulid = "1.2.1"
